# Site settings
author: Patrick Akolo 
title: Software Engineering
header-img: img/home-bg.png
email: akolo@hotmail.com
copyright_name: Patrick Akolo 
description: > # this means to ignore newlines until "baseurl:"
  Patrick's Blog spot 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Pwako11

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
